### ISSUE TITLE
 Doubt and documentation and publicity of this exciting project

### ISSUE THREAD

**Issue by HeronDA** [fvito/blockly-for-structured-text#1]
Hello:
First of all, thank you very much for your work, it is spectacular and I have been looking for something similar for some time.

I can't see how the custom blocks work and their difference with the functions. Also, they don't generate the correct code.

![Screenshot_1](https://user-images.githubusercontent.com/18337082/86588725-8b342b00-bf8c-11ea-8e03-1a43c5ef1ae2.png)

![Screenshot_2](https://user-images.githubusercontent.com/18337082/86588885-dc441f00-bf8c-11ea-8a90-f4b69b8ffc20.png)

![Screenshot_3](https://user-images.githubusercontent.com/18337082/86588888-de0de280-bf8c-11ea-8a3f-026f1ad33e1b.png)

It would be lucky if you could guide me in this regard.  In any case, I would like to continue exploring the platform and make tutorials in the same style as those carried out at www.didactronica.com but in English.

Many thanks.

**Comment by fvito** [comment]
Hello. Im actully impressed someone is trying to use this "tool". For sure I can help you, I'll also take a look at the code generation, when I have some time

**Comment by fvito** [comment]
Hello,
I have checked your example and I believe the generated code is correct. Function blocks do not return the value, but expose the output variables via a "get" block. In the program where you used the function block, under the _Function Blocks -> Used Blocks_, two new blocks should be available, _"get member"_ and _"change member"_. This blocks are generated for each function block you use in the workspace.
Example:
![image](https://user-images.githubusercontent.com/28450775/86946661-02172280-c14b-11ea-8f0a-6919977ac9fa.png)

As for the difference between functions and functions blocks, the most basic understanding is that functions blocks can be looked as a "class" object (from other languages, like C#, C++, Java). And thus, store their internal state in the PLC memory. Functions do not do that and so the function will return the same output for the same input.

Here is a nice write up of the difference between them: http://ua.automation.com/resources-tools/application-stories/programmable-logic-controller-plc/iec-61131-3-functions-and-function-blocks-what-is-the-difference
