### ISSUE TITLE
Not displaying blocks after creating new project. Window is empty.

### ISSUE THREAD

**Issue by DNRao18** [fvito/blockly-for-structured-text#2]
![image](https://user-images.githubusercontent.com/64770852/100918350-5ce85680-34fe-11eb-9410-ae84ace3a00e.png)

**Comment by DNRao18** [comment]
Even i tried to create New program then also no change.

**Comment by fvito** [comment]
Hello, how are you opening the project? I think just opening the html does not work as web browsers prevent it from loading javascript. Do you have any errors in the console?

**Comment by MicheleGalliano** [comment]
Hi, i'm currently having the same issue. How am i supposed to open the program?

**Comment by DNRao18** [comment]
> Hi, i'm currently having the same issue. How am i supposed to open the program?



> Hi, i'm currently having the same issue. How am i supposed to open the prog
